# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 自己紹介
    url: /
    weight: 10
  - name: 論文
    url: /#papers
    weight: 12
  - name: ニュース
    url: /#news
    weight: 14
  - name: プロジェクト
    url: project/
    weight: 20
  - name: 経歴
    url: experience/
    weight: 30
  # - name: Teaching
  #   url: teaching/
  #   weight: 40
